"""form_templates.archived_at

Revision ID: a16a6f709710
Revises: a38bf9c24635
Create Date: 2026-09-17 12:17:10.317324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16a6f709710'
down_revision: Union[str, Sequence[str], None] = 'a38bf9c24635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
