/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_auth_me_preferences_patch"];
        trace?: never;
    };
    "/auth/me/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Push Token
         * @description L'app registra il token Expo Push del device (idempotente; un token cambia utente se serve).
         */
        post: operations["register_push_token_auth_me_push_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/push-token/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unregister Push Token */
        delete: operations["unregister_push_token_auth_me_push_token__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Notifications
         * @description Le mie notifiche (più recenti prima), con l'evento che le ha generate.
         */
        get: operations["my_notifications_auth_me_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Registro eventi del progetto (manager): cosa è successo e quando.
         */
        get: operations["list_events_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Elenco utenti attivi: serve a chiunque per assegnare un task. Con `include_inactive` (solo admin) anche i disattivati.
         */
        get: operations["list_users_users_get"];
        put?: never;
        /**
         * Create User
         * @description Solo admin.
         */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Solo admin: nome, ruolo, attivo/disattivo, reset password. Un admin non può
         *     disattivarsi né togliersi il ruolo admin (altrimenti resta un sistema senza amministratori).
         */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/users/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users Activity
         * @description Solo admin: ultimo accesso e conteggio operazioni per utente (per la tabella utenti).
         */
        get: operations["users_activity_users_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Actions */
        get: operations["audit_actions_audit_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Registro operazioni, dal più recente. Filtri: utente, una o più azioni,
         *     progetto, entità, intervallo date (`date_to` inclusivo se solo data), testo
         *     libero su email attore / entità / IP. Paginato (`total` per la UI).
         */
        get: operations["list_audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_projects__project_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_projects__project_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_projects__project_id__plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plan Pins
         * @description Pin (non cancellati) della planimetria con conteggi di submission e task per stato.
         *
         *     Filtri (in AND tra loro, tutti sui soli record non cancellati):
         *     - `status` (ripetibile) + `assigned_to`: il pin ha almeno un task che soddisfa
         *       ENTRAMBE le condizioni (es. "task aperti assegnati a Mario");
         *     - `template_id`: il pin ha almeno una submission di quel template;
         *     - `date_from` / `date_to`: il pin, o una sua submission/task, è stato creato
         *       nell'intervallo (estremi inclusi; `date_to` con sola data copre tutto il giorno).
         *     I conteggi restano quelli totali del pin, non filtrati.
         */
        get: operations["list_plan_pins_plans__plan_id__pins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Form Templates
         * @description Template proponibili; con include_archived anche quelli archiviati (per leggere vecchie submission).
         */
        get: operations["list_form_templates_form_templates_get"];
        put?: never;
        /** Create Form Template */
        post: operations["create_form_template_form_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Form Template */
        get: operations["get_form_template_form_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Form Template
         * @description Nome/categoria/archiviazione sempre; `schema_def` solo se nessuna submission
         *     usa ancora il template (409 altrimenti: duplicare e modificare la copia).
         */
        patch: operations["update_form_template_form_templates__template_id__patch"];
        trace?: never;
    };
    "/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pin */
        post: operations["create_pin_pins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pins/{pin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pin
         * @description Pin con submissions, task e allegati (non cancellati): apertura da plan view.
         */
        get: operations["get_pin_pins__pin_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Pin
         * @description Soft-delete del pin e di tutto ciò che contiene (submission, task, allegati),
         *     così il sync propaga la cancellazione completa. Solo creatore o manager.
         */
        delete: operations["delete_pin_pins__pin_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Pin
         * @description Sposta (x/y) o rinomina un pin.
         */
        patch: operations["update_pin_pins__pin_id__patch"];
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Submission */
        post: operations["create_submission_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Submission
         * @description Modifica delle risposte (chi l'ha compilata o un manager); stesse regole di validazione della creazione.
         */
        patch: operations["update_submission_submissions__submission_id__patch"];
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_projects__project_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Stats
         * @description Numeri per la dashboard: task per stato, aperti per planimetria, moduli per template, serie giornaliera, scaduti.
         */
        get: operations["project_stats_projects__project_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task
         * @description Soft-delete (manager/admin o creatore): viaggia nel sync come ogni altra modifica.
         */
        delete: operations["delete_task_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Task
         * @description Aggiornamento parziale. Cambi di stato solo lungo TASK_TRANSITIONS (409 altrimenti);
         *     'verified' è riservato a manager/admin. Assegnare un task 'open' senza indicare
         *     lo stato lo porta automaticamente ad 'assigned'.
         */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/plans/{plan_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Plan File
         * @description Carica l'immagine della planimetria. Un PDF viene convertito in PNG
         *     (prima pagina) così tutti i client mostrano un'immagine e basta.
         *     Le dimensioni in pixel servono ai client per posizionare i pin (x/y relativi).
         */
        post: operations["upload_plan_file_plans__plan_id__file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Attachment
         * @description Crea il record (da web); i byte arrivano dopo con /attachments/{id}/upload.
         */
        post: operations["create_attachment_attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Attachment
         * @description Soft-delete di foto/firma (chi ha compilato il modulo o creato il task, oppure un manager).
         */
        delete: operations["delete_attachment_attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign Attachment
         * @description L'app chiede dove caricare i byte di un allegato già sincronizzato.
         *     Stub per l'MVP: upload diretto sull'API. In prod restituirà un presigned URL S3.
         */
        post: operations["presign_attachment_attachments_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachment_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Attachment
         * @description Carica i byte di un allegato. Idempotente: un retry sovrascrive lo stesso file.
         */
        post: operations["upload_attachment_attachments__attachment_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Serve i file dello storage (filesystem o S3) con il JWT: gli URL nel DB sono sempre /files/<key>.
         */
        get: operations["get_file_files__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Push
         * @description Riceve un batch di modifiche fatte offline sul device e le applica
         *     con upsert idempotente per id. Le entità con FK verso qualcosa che
         *     non esiste, non valide, o di progetti a cui l'utente non ha accesso
         *     vengono rifiutate singolarmente (`rejected`), il resto del batch passa.
         */
        post: operations["sync_push_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Pull
         * @description Ritorna tutte le modifiche del progetto (fatte da chiunque, su qualsiasi
         *     device) successive a `since`. Il client salva il nuovo server_time e lo
         *     userà come `since` alla sync successiva. Le righe con deleted_at
         *     valorizzato vanno rimosse localmente.
         */
        get: operations["sync_pull_sync_pull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentCreate */
        AttachmentCreate: {
            /** Id */
            id?: string | null;
            /** Submission Id */
            submission_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** File Type */
            file_type?: string | null;
        };
        /** AttachmentOut */
        AttachmentOut: {
            /** Id */
            id: string;
            /** Submission Id */
            submission_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** File Type */
            file_type?: string | null;
            /** File Url */
            file_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AttachmentSync */
        AttachmentSync: {
            /** Id */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Submission Id */
            submission_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** File Url */
            file_url?: string | null;
            /** File Type */
            file_type?: string | null;
        };
        /** AuditActionOut */
        AuditActionOut: {
            /** Action */
            action: string;
            /** Label */
            label: string;
        };
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Actor Email */
            actor_email?: string | null;
            /** Actor Name */
            actor_name?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Ip */
            ip?: string | null;
            /** User Agent */
            user_agent?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Body_upload_attachment_attachments__attachment_id__upload_post */
        Body_upload_attachment_attachments__attachment_id__upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_plan_file_plans__plan_id__file_post */
        Body_upload_plan_file_plans__plan_id__file_post: {
            /** File */
            file: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Project Id */
            project_id: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at?: string | null;
        };
        /** FormSubmissionSync */
        FormSubmissionSync: {
            /** Id */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Template Id */
            template_id: string;
            /** Pin Id */
            pin_id: string;
            /** Data Json */
            data_json: {
                [key: string]: unknown;
            };
            /** Submitted By */
            submitted_by?: string | null;
        };
        /** FormTemplateCreate */
        FormTemplateCreate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Schema Def */
            schema_def: {
                [key: string]: unknown;
            };
        };
        /** FormTemplateOut */
        FormTemplateOut: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Schema Def */
            schema_def: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Submissions Count
             * @default 0
             */
            submissions_count: number;
        };
        /**
         * FormTemplateUpdate
         * @description PATCH parziale. `schema_def` è modificabile solo finché nessuna submission usa il template.
         */
        FormTemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Schema Def */
            schema_def?: {
                [key: string]: unknown;
            } | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MemberAdd */
        MemberAdd: {
            /** User Id */
            user_id: string;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: string;
            /** Event Id */
            event_id: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at?: string | null;
            event: components["schemas"]["EventOut"];
        };
        /** PinCreate */
        PinCreate: {
            /** Plan Id */
            plan_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
        };
        /**
         * PinDetail
         * @description Pin con tutto ciò che gli è agganciato: è ciò che apre la plan view al click.
         */
        PinDetail: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Submissions
             * @default []
             */
            submissions: components["schemas"]["SubmissionOut"][];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskOut"][];
        };
        /** PinOut */
        PinOut: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PinSummary
         * @description Pin + conteggi: basta alla plan view per colorare i marker senza caricare i dettagli.
         */
        PinSummary: {
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Submissions Count
             * @default 0
             */
            submissions_count: number;
            /**
             * Tasks Open
             * @default 0
             */
            tasks_open: number;
            /**
             * Tasks Assigned
             * @default 0
             */
            tasks_assigned: number;
            /**
             * Tasks Resolved
             * @default 0
             */
            tasks_resolved: number;
            /**
             * Tasks Verified
             * @default 0
             */
            tasks_verified: number;
        };
        /** PinSync */
        PinSync: {
            /** Id */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Plan Id */
            plan_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
            /** Created By */
            created_by?: string | null;
        };
        /** PinUpdate */
        PinUpdate: {
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Label */
            label?: string | null;
        };
        /** PlanCreate */
        PlanCreate: {
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** File Url */
            file_url?: string | null;
            /** Width Px */
            width_px?: number | null;
            /** Height Px */
            height_px?: number | null;
        };
        /** PlanOut */
        PlanOut: {
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** File Url */
            file_url?: string | null;
            /** Width Px */
            width_px?: number | null;
            /** Height Px */
            height_px?: number | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Notify Email */
            notify_email?: boolean | null;
            /** Notify Push */
            notify_push?: boolean | null;
        };
        /** PresignRequest */
        PresignRequest: {
            /** Attachment Id */
            attachment_id: string;
        };
        /**
         * PresignResponse
         * @description Dove e come caricare i byte di un allegato. Oggi punta all'upload diretto
         *     sull'API; con S3 diventerà un presigned PUT e `fields`/`headers` cambieranno.
         */
        PresignResponse: {
            /** Attachment Id */
            attachment_id: string;
            /** Method */
            method: string;
            /** Upload Url */
            upload_url: string;
            /** Max Bytes */
            max_bytes: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PushTokenIn */
        PushTokenIn: {
            /** Token */
            token: string;
            /** Platform */
            platform?: string | null;
        };
        /** RejectedItem */
        RejectedItem: {
            /** Id */
            id: string;
            /** Reason */
            reason: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Project Id */
            project_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Tasks By Status */
            tasks_by_status: {
                [key: string]: number;
            };
            /** Tasks Total */
            tasks_total: number;
            /** Open By Plan */
            open_by_plan: {
                [key: string]: unknown;
            }[];
            /** Submissions By Template */
            submissions_by_template: {
                [key: string]: unknown;
            }[];
            /** Submissions Total */
            submissions_total: number;
            /** Series */
            series: components["schemas"]["StatsSeriesPoint"][];
            /** Overdue */
            overdue: number;
            /** Closed Last 7D */
            closed_last_7d: number;
            /** Pins Total */
            pins_total: number;
        };
        /** StatsSeriesPoint */
        StatsSeriesPoint: {
            /** Date */
            date: string;
            /** Created */
            created: number;
            /** Resolved */
            resolved: number;
        };
        /** SubmissionCreate */
        SubmissionCreate: {
            /** Template Id */
            template_id: string;
            /** Pin Id */
            pin_id: string;
            /** Data Json */
            data_json: {
                [key: string]: unknown;
            };
            /** Submitted By */
            submitted_by?: string | null;
        };
        /** SubmissionOut */
        SubmissionOut: {
            /** Template Id */
            template_id: string;
            /** Pin Id */
            pin_id: string;
            /** Data Json */
            data_json: {
                [key: string]: unknown;
            };
            /** Submitted By */
            submitted_by?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentOut"][];
        };
        /** SubmissionUpdate */
        SubmissionUpdate: {
            /** Data Json */
            data_json: {
                [key: string]: unknown;
            };
        };
        /**
         * SyncPullResponse
         * @description Tutto ciò che è cambiato dopo `since` per un dato progetto.
         *     Le righe con deleted_at valorizzato vanno rimosse localmente dal client.
         */
        SyncPullResponse: {
            /** Plans */
            plans: {
                [key: string]: unknown;
            }[];
            /** Form Templates */
            form_templates: {
                [key: string]: unknown;
            }[];
            /** Pins */
            pins: {
                [key: string]: unknown;
            }[];
            /** Submissions */
            submissions: {
                [key: string]: unknown;
            }[];
            /** Tasks */
            tasks: {
                [key: string]: unknown;
            }[];
            /** Attachments */
            attachments: {
                [key: string]: unknown;
            }[];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** SyncPushRequest */
        SyncPushRequest: {
            /**
             * Pins
             * @default []
             */
            pins: components["schemas"]["PinSync"][];
            /**
             * Submissions
             * @default []
             */
            submissions: components["schemas"]["FormSubmissionSync"][];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskSync"][];
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentSync"][];
        };
        /** SyncPushResponse */
        SyncPushResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            pins: components["schemas"]["SyncPushResult"];
            submissions: components["schemas"]["SyncPushResult"];
            tasks: components["schemas"]["SyncPushResult"];
            attachments: components["schemas"]["SyncPushResult"];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** SyncPushResult */
        SyncPushResult: {
            /**
             * Inserted
             * @default 0
             */
            inserted: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Skipped Ids
             * @default []
             */
            skipped_ids: string[];
            /**
             * Rejected
             * @default []
             */
            rejected: components["schemas"]["RejectedItem"][];
        };
        /** TaskCreate */
        TaskCreate: {
            /** Pin Id */
            pin_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * TaskListItem
         * @description Task + dove sta: basta alla vista task di progetto per il link "vedi sulla planimetria".
         */
        TaskListItem: {
            /** Id */
            id: string;
            /** Pin Id */
            pin_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentOut"][];
            /** Plan Id */
            plan_id: string;
            /** Plan Name */
            plan_name: string;
            /** Pin Label */
            pin_label?: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: string;
            /** Pin Id */
            pin_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Status */
            status: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentOut"][];
        };
        /** TaskSync */
        TaskSync: {
            /** Id */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Pin Id */
            pin_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Status
             * @default open
             */
            status: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * TaskUpdate
         * @description PATCH parziale: solo i campi presenti vengono modificati.
         */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * UserActivityOut
         * @description Riepilogo per utente nello spazio admin: ultimo accesso e numero di operazioni.
         */
        UserActivityOut: {
            /** User Id */
            user_id: string;
            /** Last Login */
            last_login?: string | null;
            /**
             * Actions Total
             * @default 0
             */
            actions_total: number;
            /**
             * Actions Last 30D
             * @default 0
             */
            actions_last_30d: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default field
             */
            role: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Notify Email
             * @default true
             */
            notify_email: boolean;
            /**
             * Notify Push
             * @default true
             */
            notify_push: boolean;
        };
        /**
         * UserUpdate
         * @description PATCH /users/{id} (solo admin): tutti opzionali; `password` reimposta la password.
         */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_preferences_auth_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_auth_me_push_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_push_token_auth_me_push_token__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_notifications_auth_me_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_projects__project_id__events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_activity_users_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserActivityOut"][];
                };
            };
        };
    };
    audit_actions_audit_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditActionOut"][];
                };
            };
        };
    };
    list_audit_audit_get: {
        parameters: {
            query?: {
                actor_id?: string | null;
                action?: string[] | null;
                project_id?: string | null;
                entity_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_projects__project_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_projects__project_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_projects__project_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_pins_plans__plan_id__pins_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                template_id?: string | null;
                assigned_to?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_form_templates_form_templates_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_form_template_form_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_template_form_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_form_template_form_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pin_pins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pin_pins__pin_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pin_pins__pin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pin_pins__pin_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_submission_submissions__submission_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_projects__project_id__tasks_get: {
        parameters: {
            query?: {
                status?: string | null;
                plan_id?: string | null;
                assigned_to?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_stats_projects__project_id__stats_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                template_id?: string | null;
                plan_id?: string | null;
                assigned_to?: string | null;
                days?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_plan_file_plans__plan_id__file_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_plan_file_plans__plan_id__file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attachment_attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_attachment_attachments_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_attachments__attachment_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_attachments__attachment_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_files__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_push_sync_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_pull_sync_pull_get: {
        parameters: {
            query: {
                project_id: string;
                /** @description server_time dell'ultima sync; omesso = tutto */
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
