"""support_messages (Contatta l'amministratore), events.project_id nullable

Gli eventi support.message non appartengono a un cantiere: project_id diventa opzionale.

Revision ID: 689adb9ac445
Revises: e1f4a5b6c7d8
Create Date: 2026-09-25 15:21:08.683463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689adb9ac445'
down_revision: Union[str, Sequence[str], None] = 'e1f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_support_messages_closed_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_support_messages_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Gli eventi senza cantiere (segnalazioni) non possono restare con project_id NOT NULL.
    op.execute("DELETE FROM notifications WHERE event_id IN (SELECT id FROM events WHERE project_id IS NULL)")
    op.execute("DELETE FROM events WHERE project_id IS NULL")
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_status'))
        batch_op.drop_index(batch_op.f('ix_support_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_created_at'))

    op.drop_table('support_messages')
    # ### end Alembic commands ###
