"""tasks.resolved_at

Revision ID: f14c50457629
Revises: 77ac699aabf6
Create Date: 2026-09-17 16:47:23.148614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14c50457629'
down_revision: Union[str, Sequence[str], None] = '77ac699aabf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_resolved_at'), ['resolved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_resolved_at'))
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
